language: node_js

node_js:
  # Node 10.3+ includes npm@6 which has good "npm ci" command
  - 10.8

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
    - libgconf-2-4

  override:
    - npm ci
    - npm run cy:verify

before_install:
  - cd ./frontend

install:
  - pwd
  - npm install
  - $(npm bin)/cypress install

script:
  - CYPRESS_baseUrl=https://www.paraplegie.ch $(npm bin)/cypress run